# Generated by Django 4.2 on 2024-01-30 09:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_events_created_at_events_updated_at_events_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Speakers',
            new_name='Speaker',
        ),
    ]
